import { LocalIndex } from "vectra";
import path from "path";
import type { ChunkMetadata } from "@/types/rag";
import type { VectorStore, VectorSearchResult } from "./types";

const INDEX_PATH = path.resolve(process.cwd(), ".vector-index");

/**
 * Local file-based vector store using vectra.
 *
 * vectra stores vectors as JSON files on disk. No cloud dependency,
 * no API keys, instant startup. The .vector-index/ directory is
 * gitignored (regenerated by running `npm run ingest`).
 *
 * Under the hood it uses HNSW (Hierarchical Navigable Small World)
 * graphs for approximate nearest neighbor search — the same algorithm
 * Pinecone and most production vector DBs use, just running locally.
 */
export class LocalVectorStore implements VectorStore {
  private index: LocalIndex;

  constructor() {
    this.index = new LocalIndex(INDEX_PATH);
  }

  async initialize(): Promise<void> {
    if (!(await this.index.isIndexCreated())) {
      try {
        await this.index.createIndex();
      } catch {
        // On read-only filesystems (e.g. Vercel), createIndex will fail.
        // The committed .vector-index/ should already exist in production.
      }
    }
  }

  async upsert(
    items: {
      id: string;
      vector: number[];
      metadata: ChunkMetadata & { text: string };
    }[],
  ): Promise<void> {
    await this.initialize();

    for (const item of items) {
      const { tags, ...rest } = item.metadata;
      const metadata: Record<string, string | number | boolean> = {
        ...rest,
        text: item.metadata.text,
      };
      if (tags) metadata.tags = JSON.stringify(tags);

      try {
        await this.index.insertItem({
          id: item.id,
          vector: item.vector,
          metadata,
        });
      } catch {
        await this.index.upsertItem({
          id: item.id,
          vector: item.vector,
          metadata,
        });
      }
    }
  }

  async query(vector: number[], topK: number): Promise<VectorSearchResult[]> {
    await this.initialize();

    const results = await this.index.queryItems(vector, "", topK);

    return results.map((result) => {
      const meta = result.item.metadata as Record<string, unknown>;
      return {
        id: result.item.id ?? "",
        score: result.score,
        text: (meta.text as string) ?? "",
        metadata: {
          source: meta.source as ChunkMetadata["source"],
          section: meta.section as string,
          title: meta.title as string,
          url: meta.url as string | undefined,
          tags: meta.tags as string[] | undefined,
          date: meta.date as string | undefined,
        },
      };
    });
  }
}
